// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           29
// Async Callback (empty):               1
// Total number of exported functions:  31

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    order_book_pair
    (
        order
        cancelOrders
        cancelAllOrders
        freeOrders
        setProvider
        setMinFee
        changeFirstToken
        changeSecondToken
        setAdmin
        setProviderAsh
        setRouterDex
        getAdmin
        fillOrder
        resolve
        deposit
        claim
        startGlobalOperation
        stopGlobalOperation
        getAddressOrderIds
        getOrderIdCounter
        getOrderById
        getAllOrders
        getFirstTokenId
        getSecondTokenId
        getProviderLp
        getProviderAsh
        getProviderRouter
        getFeeResolver
        getMinFee
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
